### ISSUE TITLE
Banner image not showing up

### ISSUE THREAD

**Issue by flaminghot-cheesepuff** [flaminghot-cheesepuff/masthead-semantics#1]
Hi, the banner image is not showing up even though I typed the source correctly.

@hellachella
@anna-pokhilenko

**Comment by anna-pokhilenko** [comment]
did you push after you added the banner image?

**Comment by flaminghot-cheesepuff** [comment]
I saved it and checked it on firefox

**Comment by anna-pokhilenko** [comment]
push it so I could see your code)

**Comment by flaminghot-cheesepuff** [comment]
Ok, I just did it

**Comment by anna-pokhilenko** [comment]
<img width="286" alt="Screen Shot 2021-02-08 at 2 33 25 PM" src="https://user-images.githubusercontent.com/55008926/107271776-b39c7000-6a1a-11eb-8859-693f347d020e.png">

Remove this and you will be good

**Comment by flaminghot-cheesepuff** [comment]
ok, thank you
